from .basic import DESCRIPTOR as BASIC_TEMPLATE
from .cytometry import DESCRIPTOR as CYTOMETRY_TEMPLATE
from .dual_reporter_triptych import DESCRIPTOR as DUAL_REPORTER_TRIPTYCH_TEMPLATE
from .eda import DESCRIPTOR as EDA_TEMPLATE
from .sfxi_eda import DESCRIPTOR as SFXI_EDA_TEMPLATE

BUILTIN_NOTEBOOK_TEMPLATES = (
    EDA_TEMPLATE,
    BASIC_TEMPLATE,
    CYTOMETRY_TEMPLATE,
    DUAL_REPORTER_TRIPTYCH_TEMPLATE,
    SFXI_EDA_TEMPLATE,
)

__all__ = [
    "BASIC_TEMPLATE",
    "BUILTIN_NOTEBOOK_TEMPLATES",
    "CYTOMETRY_TEMPLATE",
    "DUAL_REPORTER_TRIPTYCH_TEMPLATE",
    "EDA_TEMPLATE",
    "SFXI_EDA_TEMPLATE",
]
