from .basic import DESCRIPTOR as BASIC_TEMPLATE
from .cytometry import DESCRIPTOR as CYTOMETRY_TEMPLATE
from .eda import DESCRIPTOR as EDA_TEMPLATE
from .microplate import DESCRIPTOR as MICROPLATE_TEMPLATE
from .sfxi_eda import DESCRIPTOR as SFXI_EDA_TEMPLATE

BUILTIN_NOTEBOOK_TEMPLATES = (
    EDA_TEMPLATE,
    BASIC_TEMPLATE,
    MICROPLATE_TEMPLATE,
    CYTOMETRY_TEMPLATE,
    SFXI_EDA_TEMPLATE,
)

__all__ = [
    "BASIC_TEMPLATE",
    "BUILTIN_NOTEBOOK_TEMPLATES",
    "CYTOMETRY_TEMPLATE",
    "EDA_TEMPLATE",
    "MICROPLATE_TEMPLATE",
    "SFXI_EDA_TEMPLATE",
]
