"""Stable, task-oriented interfaces for Reader experiments and plugins."""

from .artifacts import ArtifactFileResult, read_artifact
from .facade import (
    describe_plugin,
    inspect,
    notebook,
    open_experiment,
    plan,
    plots,
    plugins,
    read_dataframe,
    records,
    run,
    validate,
    verify,
)
from .models import (
    ApiResult,
    DataFrameRecordResult,
    Experiment,
    ExperimentEvidence,
    ExperimentIdentity,
    InspectionResult,
    NotebookResult,
    PlanResult,
    PluginCatalogResult,
    PluginDescriptorResult,
    PluginPort,
    PluginSummary,
    RecordCatalogResult,
    RecordRevision,
    RunResult,
    SelectedSteps,
    SurfaceCatalogResult,
    ValidationResult,
    VerificationResult,
)

__all__ = [
    "ApiResult",
    "ArtifactFileResult",
    "DataFrameRecordResult",
    "Experiment",
    "ExperimentEvidence",
    "ExperimentIdentity",
    "InspectionResult",
    "NotebookResult",
    "PlanResult",
    "PluginCatalogResult",
    "PluginDescriptorResult",
    "PluginPort",
    "PluginSummary",
    "RecordCatalogResult",
    "RecordRevision",
    "RunResult",
    "SelectedSteps",
    "SurfaceCatalogResult",
    "ValidationResult",
    "VerificationResult",
    "describe_plugin",
    "inspect",
    "notebook",
    "open_experiment",
    "plan",
    "plots",
    "plugins",
    "read_artifact",
    "read_dataframe",
    "records",
    "run",
    "validate",
    "verify",
]
