"""Stable, task-oriented interfaces for Reader experiments and plugins."""

from .facade import describe_plugin, inspect, open_experiment, plan, plots, plugins, records, run, validate, verify
from .models import (
    ApiResult,
    Experiment,
    ExperimentEvidence,
    ExperimentIdentity,
    InspectionResult,
    PlanResult,
    PluginCatalogResult,
    PluginDescriptorResult,
    PluginPort,
    PluginSummary,
    RecordCatalogResult,
    RecordRevision,
    RunResult,
    SelectedSteps,
    SurfaceCatalogResult,
    ValidationResult,
    VerificationResult,
)

__all__ = [
    "ApiResult",
    "Experiment",
    "ExperimentEvidence",
    "ExperimentIdentity",
    "InspectionResult",
    "PlanResult",
    "PluginCatalogResult",
    "PluginDescriptorResult",
    "PluginPort",
    "PluginSummary",
    "RecordCatalogResult",
    "RecordRevision",
    "RunResult",
    "SelectedSteps",
    "SurfaceCatalogResult",
    "ValidationResult",
    "VerificationResult",
    "describe_plugin",
    "inspect",
    "open_experiment",
    "plan",
    "plots",
    "plugins",
    "records",
    "run",
    "validate",
    "verify",
]
