"""Cytometry-domain dataframe contracts."""

from __future__ import annotations

from ..model import ColumnRule, DataFrameContract

CONTRACTS: tuple[DataFrameContract, ...] = (
    DataFrameContract(
        id="cytometer.channels.v1",
        description="Per-sample cytometer channel metadata from FCS headers.",
        columns=[
            ColumnRule("sample_id", "string"),
            ColumnRule("channel_index", "int"),
            ColumnRule("channel_name", "string"),
            ColumnRule("pns", "string", required=False, allow_nan=True),
            ColumnRule("pnn", "string", required=False, allow_nan=True),
            ColumnRule("pnt", "string", required=False, allow_nan=True),
            ColumnRule("pnf", "string", required=False, allow_nan=True),
            ColumnRule("pnl", "string", required=False, allow_nan=True),
            ColumnRule("pnr", "float", required=False, allow_nan=True),
            ColumnRule("pnb", "float", required=False, allow_nan=True),
            ColumnRule("png", "float", required=False, allow_nan=True),
            ColumnRule("pne_decades", "float", required=False, allow_nan=True),
            ColumnRule("pne_zero", "float", required=False, allow_nan=True),
        ],
        unique_keys=[],
        domain="cytometry",
        kind="channel-metadata",
    ),
    DataFrameContract(
        id="cytometry.gate_definition.v1",
        description="One resolved cytometry gate, threshold, grouping, and QC definition.",
        columns=[
            ColumnRule("definition_id", "string"),
            ColumnRule("cells_enabled", "bool"),
            ColumnRule("cells_x_channel", "string"),
            ColumnRule("cells_x_min", "float"),
            ColumnRule("cells_x_max", "float"),
            ColumnRule("cells_y_channel", "string"),
            ColumnRule("cells_y_min", "float"),
            ColumnRule("cells_y_max", "float"),
            ColumnRule("singlets_enabled", "bool"),
            ColumnRule("singlet_x_channel", "string"),
            ColumnRule("singlet_y_channel", "string"),
            ColumnRule("singlet_ratio_min", "float"),
            ColumnRule("singlet_ratio_max", "float"),
            ColumnRule("fluorescence_channel", "string"),
            ColumnRule("threshold_mode", "string", allowed_values=("manual", "from_control_quantile")),
            ColumnRule("threshold_value", "float"),
            ColumnRule("threshold_group_column", "string", allow_nan=True),
            ColumnRule("threshold_control_value", "string", allow_nan=True),
            ColumnRule("threshold_quantile", "float", allow_nan=True),
            ColumnRule("group_column", "string", allow_nan=True),
            ColumnRule("minimum_final_events", "int", nonnegative=True),
            ColumnRule("minimum_final_percent", "float", nonnegative=True),
            ColumnRule("maximum_nonpositive_percent", "float", nonnegative=True),
            ColumnRule("nonpositive_scope", "string", allowed_values=("all_events", "gated_events")),
        ],
        unique_keys=[["definition_id"]],
        domain="cytometry",
        kind="gate-definition",
    ),
    DataFrameContract(
        id="cytometry.gated_events.v1",
        description="Event-wide cytometry rows that passed the resolved sequential gates.",
        columns=[
            ColumnRule("sample_id", "string"),
            ColumnRule("event_index", "int", nonnegative=True),
        ],
        unique_keys=[["sample_id", "event_index"]],
        domain="cytometry",
        kind="gated-events",
    ),
    DataFrameContract(
        id="cytometry.sample_stats.v1",
        description="Per-sample cytometry gate counts and fluorescence summaries.",
        columns=[
            ColumnRule("sample_id", "string"),
            ColumnRule("group_column", "string", allow_nan=True),
            ColumnRule("group_value", "string", allow_nan=True),
            ColumnRule("n_total_events", "int", nonnegative=True),
            ColumnRule("n_cells_gate", "int", nonnegative=True),
            ColumnRule("n_singlets", "int", nonnegative=True),
            ColumnRule("pct_cells", "float", nonnegative=True),
            ColumnRule("pct_singlets_of_cells", "float", nonnegative=True),
            ColumnRule("pct_final", "float", nonnegative=True),
            ColumnRule("fluor_median", "float", allow_nan=True),
            ColumnRule("fluor_mean", "float", allow_nan=True),
            ColumnRule("fluor_geomean", "float", allow_nan=True),
            ColumnRule("fluor_p90", "float", allow_nan=True),
            ColumnRule("fluor_p99", "float", allow_nan=True),
            ColumnRule("pct_positive", "float", nonnegative=True, allow_nan=True),
            ColumnRule("fluorescence_channel", "string"),
            ColumnRule("threshold_value", "float"),
        ],
        unique_keys=[["sample_id"]],
        domain="cytometry",
        kind="sample-statistics",
    ),
    DataFrameContract(
        id="cytometry.group_stats.v1",
        description="Explicitly grouped cytometry sample summaries; empty when grouping is disabled.",
        columns=[
            ColumnRule("group_column", "string"),
            ColumnRule("group_value", "string"),
            ColumnRule("n_samples", "int", nonnegative=True),
            ColumnRule("fluor_median_mean", "float", allow_nan=True),
            ColumnRule("fluor_median_std", "float", allow_nan=True),
            ColumnRule("fluor_geomean_mean", "float", allow_nan=True),
            ColumnRule("pct_positive_mean", "float", nonnegative=True, allow_nan=True),
        ],
        unique_keys=[["group_column", "group_value"]],
        domain="cytometry",
        kind="group-statistics",
    ),
    DataFrameContract(
        id="cytometry.qc.v1",
        description="Per-sample cytometry QC evaluated against explicit retention and signal policies.",
        columns=[
            ColumnRule("sample_id", "string"),
            ColumnRule("n_total_events", "int", nonnegative=True),
            ColumnRule("n_cells_gate", "int", nonnegative=True),
            ColumnRule("n_singlets", "int", nonnegative=True),
            ColumnRule("pct_final", "float", nonnegative=True),
            ColumnRule("pct_nonpositive", "float", nonnegative=True),
            ColumnRule("minimum_final_events", "int", nonnegative=True),
            ColumnRule("minimum_final_percent", "float", nonnegative=True),
            ColumnRule("maximum_nonpositive_percent", "float", nonnegative=True),
            ColumnRule("nonpositive_scope", "string", allowed_values=("all_events", "gated_events")),
            ColumnRule("passes_final_events", "bool"),
            ColumnRule("passes_final_percent", "bool"),
            ColumnRule("passes_nonpositive", "bool"),
            ColumnRule("qc_pass", "bool"),
            ColumnRule("qc_status", "string", allowed_values=("pass", "fail")),
        ],
        unique_keys=[["sample_id"]],
        domain="cytometry",
        kind="quality-control",
    ),
)
